# -*- coding: utf-8 -*-
"""vicreg

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L9b-GBCFsF0ND2CYyfBP0fSmxzZ1QUTD

# VICReg out-of-distribution class classification benchmark

##Acknowledgments

https://github.com/baxterai/vicreg/tree/branch-distributedExecutionOption (non-distributedExecution of Meta VICReg repository)

* https://github.com/facebookresearch/vicreg

##Setup

###Set up VICreg code, datasets, folder structure;
"""

#import vicreg code and datasets:
#warning: executing this code block will overwrite all source/data files in memory

from google.colab import drive
drive.mount('/content/gdrive')

!cp -av gdrive/My\ Drive/code/vicreg .
!unzip gdrive/My\ Drive/code/datasets/imagenette2-320.zip
!unzip gdrive/My\ Drive/code/datasets/imagenette2-320-half.zip

#note imagenette2-320-half contains 50% of classes of imagenette2-320 train/val data

#create experiment output folders:
#!mkdir exp
!mkdir expbp
!mkdir expvr

#import existing/saved models (if available)
#!cp -av gdrive/My\ Drive/code/expbp/* expbp/
#!cp -av gdrive/My\ Drive/code/expvr/* expvr/

"""###Trial vicreg code (test only based on README.md);"""

#Single-node local training
#!python vicreg/main_vicreg-nonDistributed.py --data-dir ./imagenette2-320 --exp-dir ./exp --arch resnet50 --epochs 1 --batch-size 64 --base-lr 0.3

#Linear evaluation
#!python vicreg/evaluate-nonDistributed.py --data-dir ./imagenette2-320 --pretrained ./exp/resnet50.pth --exp-dir ./exp --epochs 1 --lr-head 0.02

"""##Test out-of-distribution class classification after Backprop vs VICReg model backbone training;
- expbp: Resnet-50 top 1 performance trained on 50% of images with Backprop, evaluate top-1 performance when only training final layer [ie linear classifier] on 100% images
- expvr: Resnet-50 top 1 performance trained on 50% of images with VICREG, evaluate top-1 performance when only training final layer [ie linear classifier] on 100% images

###expbp (backprop 50% training, 100% linear eval);
"""

#do not train, just generate model for evaluate input (expbp/resnet50.pth)
!python vicreg/main_vicreg-nonDistributed.py --data-dir ./imagenette2-320-half --exp-dir ./expbp --arch resnet50 --epochs 1 --batch-size 64 --base-lr 0.3

#Backprop hidden layer training with 50% classes
!python vicreg/evaluate-nonDistributed.py --data-dir ./imagenette2-320-half --pretrained ./expbp/resnet50.pth --exp-dir ./expbp --epochs 100 --batch-size 64 --weights finetune --train-perc 100 --lr-backbone 0.3 --lr-head 0.08 --weight-decay 0

#Linear evaluation with 100% classes
!python vicreg/evaluate-nonDistributed.py --data-dir ./imagenette2-320 --pretrained ./expbp/resnet50eval-atEpoch75.pth --exp-dir ./expbp --epochs 100 --batch-size 64 --weights freeze --lr-head 0.02

"""###expvr (vicreg 50% training, 100% linear eval);"""

#VICReg hidden layer training with 50% classes
!python vicreg/main_vicreg-nonDistributed.py --data-dir ./imagenette2-320-half --exp-dir ./expvr --epochs 100 --batch-size 64 --arch resnet50 --batch-size 64 --base-lr 0.3

#Linear evaluation with 100% classes
!python vicreg/evaluate-nonDistributed.py --data-dir ./imagenette2-320 --pretrained ./expvr/resnet50.pth --exp-dir ./expvr --epochs 100 --batch-size 64 --weights freeze --lr-head 0.02